### ISSUE TITLE
Update Developer Guide for v1.1

### ISSUE THREAD

**Issue by creativequotient** [AY2021S2-CS2103T-W15-3/tp#9]

**Comment by IanCKW** [comment]
Target user profile, value proposition, user stories, and use cases added. Glossary and NFRs are kept the same

**Comment by Sharptail** [comment]
Reopen to link PR

**Comment by Sharptail** [comment]
Reopen to link PR

**Comment by Sharptail** [comment]
Reopen to remove traces of AB-3

**Comment by Sharptail** [comment]
Fixed by #28
